//! Client-side WaveSyncDB passphrase derivation.

use argon2::{Algorithm, Argon2, Params, Version};

use crate::error::PocketBaseError;

/// Derive a 64-char hex PSK from `(user_id, password)` via Argon2id.
///
/// Salt is `psk_domain || user_id` so the same password gives different PSKs
/// across users and across apps (each app supplies its own domain tag, e.g.
/// `b"ascend.psk.v1|"`). User-id is used rather than email so an email change
/// doesn't rotate the key. Every device that authenticates with the same
/// email + password lands on the same PSK, so they can join the same
/// gossipsub topic without the server ever holding the key.
///
/// Argon2id parameters are the OWASP 2024 baseline (m=19 MiB, t=2, p=1) —
/// fast enough on mobile (~100ms), expensive enough that brute-forcing stays
/// out of reach for low-entropy passwords.
///
/// # Compatibility
///
/// The parameters and salt layout are load-bearing: existing users' WaveSync
/// passphrases were derived with exactly this construction. Golden-vector
/// tests below lock it — do not change either without a migration story.
pub fn derive_psk(
    psk_domain: &[u8],
    user_id: &str,
    password: &str,
) -> Result<String, PocketBaseError> {
    if user_id.is_empty() {
        return Err(PocketBaseError::Crypto("empty user_id".into()));
    }
    let params = Params::new(19_456, 2, 1, Some(32))
        .map_err(|e| PocketBaseError::Crypto(format!("argon2 params: {e}")))?;
    let argon = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let mut salt = Vec::with_capacity(psk_domain.len() + user_id.len());
    salt.extend_from_slice(psk_domain);
    salt.extend_from_slice(user_id.as_bytes());
    let mut out = [0u8; 32];
    argon
        .hash_password_into(password.as_bytes(), &salt, &mut out)
        .map_err(|e| PocketBaseError::Crypto(format!("argon2 derive: {e}")))?;
    Ok(hex::encode(out))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Golden vector generated by MediterraneaDiente's production
    /// `dto::derive_psk("user123", "hunter2")` (2026-07-02). If this test
    /// fails, existing Mediterranea users' WaveSync passphrases would rotate
    /// on migration — do not "fix" the expected value.
    #[test]
    fn golden_vector_mediterranea_domain() {
        assert_eq!(
            derive_psk(b"mediterranea.psk.v1|", "user123", "hunter2").unwrap(),
            "e9e733dfae47e301d0da77dc83d25d1f12e02b62eb9579e32a5297bcd09301df"
        );
    }

    /// Golden vector for Ascend's domain tag, generated with the same
    /// algorithm validated against Mediterranea's production code (Ascend's
    /// `derive_psk` is a verbatim copy differing only in the domain const).
    #[test]
    fn golden_vector_ascend_domain() {
        assert_eq!(
            derive_psk(b"ascend.psk.v1|", "user123", "hunter2").unwrap(),
            "3fb4ccc9e97eab3406da394003847b1c0547bcf84eb8798bedc075deaac47ecd"
        );
    }

    #[test]
    fn deterministic_hex_and_scoped() {
        let a = derive_psk(b"test.psk.v1|", "user123", "hunter2").unwrap();
        let b = derive_psk(b"test.psk.v1|", "user123", "hunter2").unwrap();
        assert_eq!(a, b);
        assert_eq!(a.len(), 64);
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
        // Different users, passwords, and domains must never collide.
        assert_ne!(
            derive_psk(b"test.psk.v1|", "alice", "shared").unwrap(),
            derive_psk(b"test.psk.v1|", "bob", "shared").unwrap()
        );
        assert_ne!(
            derive_psk(b"test.psk.v1|", "user123", "old").unwrap(),
            derive_psk(b"test.psk.v1|", "user123", "new").unwrap()
        );
        assert_ne!(
            derive_psk(b"app-a.psk.v1|", "user123", "pw").unwrap(),
            derive_psk(b"app-b.psk.v1|", "user123", "pw").unwrap()
        );
    }

    #[test]
    fn rejects_empty_user_id() {
        assert!(matches!(
            derive_psk(b"test.psk.v1|", "", "x"),
            Err(PocketBaseError::Crypto(_))
        ));
    }

    /// Argon2 requires an ≥8-byte salt; `domain + user_id` shorter than that
    /// surfaces as a Crypto error rather than a panic. Real PocketBase ids
    /// are 15 chars, so this only matters for degenerate inputs.
    #[test]
    fn too_short_salt_is_a_clean_error() {
        assert!(matches!(
            derive_psk(b"t|", "u", "pw"),
            Err(PocketBaseError::Crypto(_))
        ));
    }
}
